### ISSUE TITLE
Helpstring in gen_client is incorrect for discovery_url

### ISSUE THREAD

**Issue by dhermes** [google/apitools#20]
The `gen_client help` [says][1]

```
  --discovery_url: URL (or "name/version") of the ...
```

but the code [rejects][2] if it doesn't come in the form `name.version`.

----

Example stacktrace:

```bash
$ gen_client --discovery_url="storage/v1" --outdir=foo client
Traceback (most recent call last):
  File "/usr/local/bin/gen_client", line 9, in <module>
    load_entry_point('google-apitools==0.4.1', 'console_scripts', 'gen_client')()
  File "/usr/local/lib/python2.7/dist-packages/apitools/gen/gen_client.py", line 240, in run_main
    appcommands.Run()
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/appcommands.py", line 791, in Run
    return app.run()
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/app.py", line 238, in run
    return _actual_start()
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/app.py", line 267, in _actual_start
    really_start()
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/appcommands.py", line 788, in InterceptReallyStart
    original_really_start(main=_CommandsStart)
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/appcommands.py", line 773, in _CommandsStart
    sys.exit(command.CommandRun(GetCommandArgv()))
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/appcommands.py", line 293, in CommandRun
    ret = self.Run(argv)
  File "/usr/local/lib/python2.7/dist-packages/apitools/gen/gen_client.py", line 203, in Run
    codegen = _GetCodegenFromFlags()
  File "/usr/local/lib/python2.7/dist-packages/apitools/gen/gen_client.py", line 109, in _GetCodegenFromFlags
    discovery_doc = util.FetchDiscoveryDoc(FLAGS.discovery_url)
  File "/usr/local/lib/python2.7/dist-packages/apitools/gen/util.py", line 289, in FetchDiscoveryDoc
    discovery_url = NormalizeDiscoveryUrl(discovery_url)
  File "/usr/local/lib/python2.7/dist-packages/apitools/gen/util.py", line 281, in NormalizeDiscoveryUrl
    raise ValueError('Unrecognized value "%s" for discovery url')
ValueError: Unrecognized value "%s" for discovery url
```

[1]: https://github.com/google/apitools/blob/4062e9f7e7fee7b082913a47df4ecb8f0619ea9e/apitools/gen/gen_client.py#L24
[2]: https://github.com/google/apitools/blob/4062e9f7e7fee7b082913a47df4ecb8f0619ea9e/apitools/gen/util.py#L280-L281

**Comment by dhermes** [comment]
:+1:
