### ISSUE TITLE
gen_client stacktrace with python 3.13

### ISSUE THREAD

**Issue by smoser** [google/apitools#327]
Trying to use google-apitools for python3.13 causes stacktrace in `gen_client --help`

```
# python3.13 -m pip install --root-user-action=ignore google-apitools
Collecting google-apitools
  Downloading google_apitools-0.5.32-py3-none-any.whl.metadata (2.3 kB)
Collecting httplib2>=0.8 (from google-apitools)
  Downloading httplib2-0.22.0-py3-none-any.whl.metadata (2.6 kB)
Collecting fasteners>=0.14 (from google-apitools)
  Downloading fasteners-0.19-py3-none-any.whl.metadata (4.9 kB)
Collecting oauth2client>=1.4.12 (from google-apitools)
  Downloading oauth2client-4.1.3-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting six>=1.12.0 (from google-apitools)
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 (from httplib2>=0.8->google-apitools)
  Downloading pyparsing-3.2.0-py3-none-any.whl.metadata (5.0 kB)
Collecting pyasn1>=0.1.7 (from oauth2client>=1.4.12->google-apitools)
  Downloading pyasn1-0.6.1-py3-none-any.whl.metadata (8.4 kB)
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=1.4.12->google-apitools)
  Downloading pyasn1_modules-0.4.1-py3-none-any.whl.metadata (3.5 kB)
Collecting rsa>=3.1.4 (from oauth2client>=1.4.12->google-apitools)
  Downloading rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Downloading google_apitools-0.5.32-py3-none-any.whl (135 kB)
Downloading fasteners-0.19-py3-none-any.whl (18 kB)
Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
Downloading oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
Downloading pyasn1_modules-0.4.1-py3-none-any.whl (181 kB)
Downloading pyparsing-3.2.0-py3-none-any.whl (106 kB)
Downloading rsa-4.9-py3-none-any.whl (34 kB)
Installing collected packages: six, pyparsing, pyasn1, fasteners, rsa, pyasn1-modules, httplib2, oauth2client, google-apitools
Successfully installed fasteners-0.19 google-apitools-0.5.32 httplib2-0.22.0 oauth2client-4.1.3 pyasn1-0.6.1 pyasn1-modules-0.4.1 pyparsing-3.2.0 rsa-4.9 six-1.16.0

# gen_client --help
Traceback (most recent call last):
  File "/usr/bin/gen_client", line 5, in <module>
    from apitools.gen.gen_client import main
  File "/usr/lib/python3.13/site-packages/apitools/gen/gen_client.py", line 28, in <module>
    from apitools.base.py import exceptions
  File "/usr/lib/python3.13/site-packages/apitools/base/py/__init__.py", line 21, in <module>
    from apitools.base.py.base_api import *
  File "/usr/lib/python3.13/site-packages/apitools/base/py/base_api.py", line 31, in <module>
    from apitools.base.protorpclite import message_types
  File "/usr/lib/python3.13/site-packages/apitools/base/protorpclite/message_types.py", line 25, in <module>
    from apitools.base.protorpclite import messages
  File "/usr/lib/python3.13/site-packages/apitools/base/protorpclite/messages.py", line 549, in <module>
    class Variant(Enum):
    ...<34 lines>...
        SINT64 = 18
  File "/usr/lib/python3.13/site-packages/apitools/base/protorpclite/messages.py", line 319, in __init__
    raise EnumDefinitionError(
    ...<2 lines>...
        (attribute, value))
apitools.base.protorpclite.messages.EnumDefinitionError: May only use integers in Enum definitions.  Found: __static_attributes__ = ()
```

**Comment by potiuk** [comment]
Indeed that would be cool if tthere is a release with it,
