### ISSUE TITLE
Running tox locally on Ubuntu 14.04 fails

### ISSUE THREAD

**Issue by dhermes** [google/apitools#4]
With a brand-new checkout, running `tox -e py27` fails with

```python
======================================================================
ERROR: testGeneration (apitools.gen.client_generation_test.ClientGenerationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../apitools/apitools/gen/client_generation_test.py", line 61, in testGeneration
    retcode = subprocess.call(args)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
-------------------- >> begin captured logging << --------------------
root: INFO: Testing API drive.v2 with command line: gen_client --client_id=12345 --client_secret=67890 --discovery_url=drive.v2 --outdir=generated --overwrite client
--------------------- >> end captured logging << ---------------------
```

**Comment by dhermes** [comment]
OK this passed on the second run, but it's still an issue for the first run. I suppose the focus of this bug should be on that instead.

Secondary question: Is there really onlt 61 unit tests for this whole codebase? Running

```
git ls-files | grep -e 'py$' | egrep -v test | egrep -v setup | xargs wc -l
```

yields 12981 lines of code. 61 unit tests?

**Comment by dhermes** [comment]
Running

```
$ nosetests -v --collect-only
testAdditionalHeaders (apitools.base.py.base_api_test.BaseApiTest) ... ok
testIncludeEmptyFieldsClient (apitools.base.py.base_api_test.BaseApiTest) ... ok
testJsonResponse (apitools.base.py.base_api_test.BaseApiTest) ... ok
testNoCredentials (apitools.base.py.base_api_test.BaseApiTest) ... ok
testPathRemapping (apitools.base.py.base_api_test.BaseApiTest) ... ok
testPrettyPrintEncoding (apitools.base.py.base_api_test.BaseApiTest) ... ok
testQueryEncoding (apitools.base.py.base_api_test.BaseApiTest) ... ok
testQueryRemapping (apitools.base.py.base_api_test.BaseApiTest) ... ok
testUrlNormalization (apitools.base.py.base_api_test.BaseApiTest) ... ok
testArbitraryLengthRead (apitools.base.py.buffered_stream_test.BufferedStreamTest) ... ok
testEmptyBuffer (apitools.base.py.buffered_stream_test.BufferedStreamTest) ... ok
testExhaustedStream (apitools.base.py.buffered_stream_test.BufferedStreamTest) ... ok
testOffsetStream (apitools.base.py.buffered_stream_test.BufferedStreamTest) ... ok
testUnexhaustedStream (apitools.base.py.buffered_stream_test.BufferedStreamTest) ... ok
testGceServiceAccounts (apitools.base.py.credentials_lib_test.CredentialsLibTest) ... ok
testAdditionalMessageProperties (apitools.base.py.encoding_test.EncodingTest) ... ok
testAdditionalPropertyMapping (apitools.base.py.encoding_test.EncodingTest) ... ok
testBytesEncoding (apitools.base.py.encoding_test.EncodingTest) ... ok
testCopyProtoMessage (apitools.base.py.encoding_test.EncodingTest) ... ok
testEnumRemapping (apitools.base.py.encoding_test.EncodingTest) ... ok
testFieldRemapping (apitools.base.py.encoding_test.EncodingTest) ... ok
testIgnoredEnums (apitools.base.py.encoding_test.EncodingTest) ... ok
testIgnoredEnumsWithDefaults (apitools.base.py.encoding_test.EncodingTest) ... ok
testIncludeFields (apitools.base.py.encoding_test.EncodingTest) ... ok
testJsonDatetime (apitools.base.py.encoding_test.EncodingTest) ... ok
testMessageToRepr (apitools.base.py.encoding_test.EncodingTest) ... ok
testMessageToReprWithTime (apitools.base.py.encoding_test.EncodingTest) ... ok
testMultipleRemapping (apitools.base.py.encoding_test.EncodingTest) ... ok
testNestedFieldMapping (apitools.base.py.encoding_test.EncodingTest) ... ok
testNestedIncludeFields (apitools.base.py.encoding_test.EncodingTest) ... ok
testNoRepeatedRemapping (apitools.base.py.encoding_test.EncodingTest) ... ok
testRepeatedEnumRemapping (apitools.base.py.encoding_test.EncodingTest) ... ok
testRepeatedFieldRemapping (apitools.base.py.encoding_test.EncodingTest) ... ok
testUnknownNestedRoundtrip (apitools.base.py.encoding_test.EncodingTest) ... ok
testValidEnums (apitools.base.py.encoding_test.EncodingTest) ... ok
testArrayAsValue (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testArrayEncoding (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testDateField (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testDictEncoding (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testInt64 (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testInvalidProtos (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testJsonNumberEncoding (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testJsonObjectPropertyTranslation (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testNullEncoding (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testObjectAsValue (apitools.base.py.extra_types_test.ExtraTypesTest) ... ok
testRequestBodyUsesLengthProperty (apitools.base.py.http_wrapper_test.HttpWrapperTest) ... ok
testRequestBodyWithLen (apitools.base.py.http_wrapper_test.HttpWrapperTest) ... ok
testEmptySlice (apitools.base.py.stream_slice_test.StreamSliceTest) ... ok
testOffsetStream (apitools.base.py.stream_slice_test.StreamSliceTest) ... ok
testSimpleSlice (apitools.base.py.stream_slice_test.StreamSliceTest) ... ok
testTooShortStream (apitools.base.py.stream_slice_test.StreamSliceTest) ... ok
Test a specific corner case in multipart encoding. ... ok
testAcceptableMimeType (apitools.base.py.util_test.UtilTest) ... ok
testCalculateWaitForRetry (apitools.base.py.util_test.UtilTest) ... ok
testExpand (apitools.base.py.util_test.UtilTest) ... ok
testMapParamNames (apitools.base.py.util_test.UtilTest) ... ok
testMapRequestParams (apitools.base.py.util_test.UtilTest) ... ok
testReservedExpansion (apitools.base.py.util_test.UtilTest) ... ok
testTypecheck (apitools.base.py.util_test.UtilTest) ... ok
testUnsupportedMimeType (apitools.base.py.util_test.UtilTest) ... ok
testGeneration (apitools.gen.client_generation_test.ClientGenerationTest) ... ok

----------------------------------------------------------------------
Ran 61 tests in 0.530s

OK
```

**Comment by dhermes** [comment]
Classifying these by file, we see the two test files missing:

```
samples/storage_sample/downloads_test.py
samples/storage_sample/uploads_test.py
```

**Comment by craigcitro** [comment]
so there are a few things going on in this thread:

* i can't repro the `tox` failure. the failing test requires network access, which is all kinds of dirty -- but the failure here seems to be something else entirely. can we confirm that it's failing to find `gen_client` itself? is there anything else further up in the log that looks fishy?

* test coverage is fishy in part because i haven't yet gotten all of the internal tests untangled enough to run externally. low coverage numbers on a shield in readme will hopefully be good motivation. :smile: 

* much of the test coverage here is in the form of integration tests, not unit tests -- lots of experience shows that trying to mock out either (1) the discovery docs or (2) server behavior only gives a false sense of security. i think this means i'll ultimately need to wire up the coveralls reporting to tests that use a service account in travis.

**Comment by dhermes** [comment]
@craigcitro Here is the entire output of a fresh run:
https://gist.github.com/dhermes/9c64db03dd0cc01e852b

We (`gcloud-python`) use a service account in our regression/system tests, but our unit tests are very fast because we don't have any file I/O and don't have any network I/O.

**Comment by craigcitro** [comment]
yeah, so we're going to drop this from the unit tests -- but i'd still love to know exactly what's failing there. 

you down with me sending you an extra patch with some debugging print statements to rerun with?

**Comment by dhermes** [comment]
Yes, very much so.

**Comment by craigcitro** [comment]
https://github.com/craigcitro/apitools/tree/morelogging has some extra logging, so we can at least confirm why we're failing.

**Comment by dhermes** [comment]
Running `morelogging` didn't really log much else: https://gist.github.com/dhermes/74b64447970b9957834e
